### ISSUE TITLE
Cash cushion

### ISSUE THREAD

**Issue by danielabar** [danielabar/retirement_drawdown_simulator_canada#12]
Add a new configurable account type cash or cash_cushion, something like this in `inputs.yml`:
```yml
accounts:
  rrsp: 865627
  taxable: 532215
  tfsa: 160325
  # NEW (also taxable, but not investments)
  cash_cushion:
    balance: 40000
    interest_rate: 0.005
``` 

If the market return in any given year is below X, then drawdown that year's spending from cash cushion instead of investment account(s).

TBD:
- what should X be, for example, more than 1 standard deviation below average?
- handle partial? eg: cash cushion may not be large enough for an entire year's spending needs
- only withdraw desired_spending, not the optional/additional TFSA contribution (because this cash cushion is intended only to weather storms)
- if the storm occurs during RRSP drawdown phase, and there's not enough in cash cushion for a full year's spending, this is complicated because the RRSP withdrawals are larger than what's needed to account for income taxes; whereas cash_cushion withdrawals are after-tax

Out of scope:
- replenish cash cushion during above average market return years (future ticket)
- tax implications of interest earned on this account (which is a taxable account)
